### ISSUE TITLE
phylo_path errors when parallel is not NULL

### ISSUE THREAD

**Issue by SimonGreenhill** [Ax3man/phylopath#16]
However, whenever I start a cluster e.g. 

```
result <- phylo_path(all_models, 
                     data = data_use, 
                     tree = tree, 
                     model = 'lambda',
                     method = "logistic_MPLE"
                     , parallel = “FORK"
)
```

… the analysis fails — with "Error: $ operator is invalid for atomic vectors”

It’s easy to replicate, just set the parallel flag to either ‘FORK’ or ‘SOCK’ and it happens.

**Comment by Ax3man** [comment]
Thanks for the report! That's unfortunate. This is quite an odd bug.

Reprex:

```
library(phylopath)
candidates <- define_model_set(
  A = NL ~ BM,
  B = NL ~ LS,
  .common = c(LS ~ BM, DD ~ NL)
)
p <- phylo_path(candidates, rhino, rhino_tree, parallel = "SOCK")

```
I just pushed a patch that I think should fix this. Can you install with `remote::install_github("Ax3man/phylopath")` and try again and confirm? Thanks again!

**Comment by SimonGreenhill** [comment]
Ahh, ok, I guess maybe the summary.* functions aren't exported to the cluster? Looks like it's working now, thanks for the quick fix!

**Comment by Ax3man** [comment]
Yes, for some reason the S3 dispatch is failing, but only on the cluster.

I didn't catch it, since when developing I load the package using `devtools::load_all(".")`, and it was working fine. Not sure when/why it broke, but happy it is working once more. All open to ideas though, I'd like to know why it failed.

**Comment by SimonGreenhill** [comment]
Hmm, spoke too soon.

**Comment by SimonGreenhill** [comment]
it appears that despite creating a cluster, it doesn't seem to use it. I'm not sure why, I've swapped out `pblapply` [here](https://github.com/Ax3man/phylopath/blob/master/R/phylopath.R#L103) with parlapply, and it still doesn't work, so I'm not sure what's happening (it's not plbapply, and I don't think it's a misformatted closure in the pblapply block as I've swapped that in and out).

**Comment by Ax3man** [comment]
I can confirm that it is running in parallel on my end, with both `"SOCK"` and `"FORK"`. How are you verifying that it isn't working?

**Comment by SimonGreenhill** [comment]
Very strange -- it seems to spawn the workers but doesn't use them. I've tried both FORK and SOCK on OSX. Trying this on linux works fine, so at this stage I'll chalk it up to a weird OSX glitch or something in my configuration. Thanks!

**Comment by Ax3man** [comment]
Ok, that is still disappointing though. Does `parLapply` work correctly outside of `phylo_path`? I can only test on linux and windows unfortunately.

For what it is worth, I was planning to revise the parallel implementation to use the `future` package instead. I like that framework a lot more, and it gives users much more flexibility. Perhaps that will fix your issue at some point in the future.

**Comment by SimonGreenhill** [comment]
Yes, parLapply works happily. However, running it on my cluster isn't happy -- I've got 40 CPUs per cluster node and this runs for a while before draining all the RAM and choking, so I'll probably hack phylopath to limit the number of CPUs it can create rather than `parallel::detectCores() -1`.

It might be nice to look for an instantiated cluster object using `parallel::getDefaultCluster` or allow passing a cluster object?

And yes, `future` looks much nicer, futures make more sense to me as an API in general though!
